### ISSUE TITLE
fix: use remove method with OC to conform SQL ORM

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxd#602] opened 2022-04-27 15:48 UTC
We need to update `GluuPersistenceService` to use ORM methods:
```
	<T> void remove(String primaryKey, Class<T> entryClass);
	<T> void removeByDn(String dn, String[] objectClasses);
```
instead of deprecated:
```
void remove(String dn);
```

**Comment by duttarnab** [comment] 2022-04-28 06:35
The issue is fixed in `master` and `version_4.4.0`

**Closed by duttarnab** 2022-04-28 06:35 UTC
